In [1]:

import numpy as np
import pandas as pd
import requests
from lib.odds import Odds

In [2]:
df = Odds().get_sports()

In [3]:
import pygwalker as pg

In [2]:
df = Odds().get_nba_champ_odds()

Number of events: 1

In [58]:
display(df.query("group == 'Basketball'"))

,key,group,title,description,active,has_outrights
5,basketball_euroleague,Basketball,Basketball Euroleague,Basketball Euroleague,True,False
6,basketball_nba,Basketball,NBA,US Basketball,True,False
7,basketball_nba_championship_winner,Basketball,NBA Championship Winner,Championship Winner 2024/2025,True,True
8,basketball_ncaab,Basketball,NCAAB,US College Basketball,True,False
9,basketball_ncaab_championship_winner,Basketball,NCAAB Championship Winner,US College Basketball Championship Winner,True,True

In [7]:
Odds.append_to_table(df, 'nba_champ_odds')

AttributeError: type object 'Odds' has no attribute 'append_to_table'

In [4]:
from datetime import datetime, timedelta

# Get current ISO time
current_iso_time = datetime.now().replace(microsecond=0).strftime("%Y-%m-%dT%H:%M:%SZ")

print("Current ISO Time: ", current_iso_time)

# Calculate 20 hours from now
future_time = datetime.now() + timedelta(hours=20)
future_iso_time = future_time.replace(microsecond=0).strftime("%Y-%m-%dT%H:%M:%SZ")

print("20 Hours From Now (ISO Time): ", future_iso_time)

Current ISO Time:  2024-11-13T12:42:26Z
20 Hours From Now (ISO Time):  2024-11-14T08:42:26Z

In [5]:


sport = 'basketball_nba'
odds_response = requests.get(
    f'https://api.the-odds-api.com/v4/sports/{sport}/odds',
    params={
        'api_key': '2b1fbcaa5cf9bbfca66c986129524664',
        'regions': 'us',
        'markets': 'h2h',
        'oddsFormat': 'american',
        'dateFormat': 'iso',
        'bookmakers': ['betmgm', 'fanduel', 'draftkings'],
        'commenceTimeFrom': current_iso_time,
        'commenceTimeTo': future_iso_time
    }
)

if odds_response.status_code != 200:
    print(f'Failed to get odds: status_code {odds_response.status_code}, response body {odds_response.text}')

else:
    odds_json = odds_response.json()
    print('Number of events:', len(odds_json))
    print(odds_json)

    # Check the usage quota
    print('Remaining requests', odds_response.headers['x-requests-remaining'])
    print('Used requests', odds_response.headers['x-requests-used'])

Number of events: 11
[{'id': 'da66702637cc0413553b92c792a05c50', 'sport_key': 'basketball_nba', 'sport_title': 'NBA', 'commence_time': '2024-11-14T00:10:00Z', 'home_team': 'Orlando Magic', 'away_team': 'Indiana Pacers', 'bookmakers': [{'key': 'betmgm', 'title': 'BetMGM', 'last_update': '2024-11-13T19:41:42Z', 'markets': [{'key': 'h2h', 'last_update': '2024-11-13T19:41:42Z', 'outcomes': [{'name': 'Indiana Pacers', 'price': -115}, {'name': 'Orlando Magic', 'price': -105}]}]}]}, {'id': '8e4ee6d0217de06a9defe24875b1b24e', 'sport_key': 'basketball_nba', 'sport_title': 'NBA', 'commence_time': '2024-11-14T00:40:00Z', 'home_team': 'Brooklyn Nets', 'away_team': 'Boston Celtics', 'bookmakers': [{'key': 'betmgm', 'title': 'BetMGM', 'last_update': '2024-11-13T19:41:42Z', 'markets': [{'key': 'h2h', 'last_update': '2024-11-13T19:41:42Z', 'outcomes': [{'name': 'Boston Celtics', 'price': -375}, {'name': 'Brooklyn Nets', 'price': 290}]}]}]}, {'id': 'ca4ada15a7c62966e17f7eecb36b2745', 'sport_key': 'basketball_nba', 'sport_title': 'NBA', 'commence_time': '2024-11-14T00:40:00Z', 'home_team': 'New York Knicks', 'away_team': 'Chicago Bulls', 'bookmakers': [{'key': 'betmgm', 'title': 'BetMGM', 'last_update': '2024-11-13T19:41:42Z', 'markets': [{'key': 'h2h', 'last_update': '2024-11-13T19:41:42Z', 'outcomes': [{'name': 'Chicago Bulls', 'price': 230}, {'name': 'New York Knicks', 'price': -275}]}]}]}, {'id': '479ed48e101593d026f662ec12a3c984', 'sport_key': 'basketball_nba', 'sport_title': 'NBA', 'commence_time': '2024-11-14T00:40:00Z', 'home_team': 'Philadelphia 76ers', 'away_team': 'Cleveland Cavaliers', 'bookmakers': [{'key': 'betmgm', 'title': 'BetMGM', 'last_update': '2024-11-13T19:41:42Z', 'markets': [{'key': 'h2h', 'last_update': '2024-11-13T19:41:42Z', 'outcomes': [{'name': 'Cleveland Cavaliers', 'price': -550}, {'name': 'Philadelphia 76ers', 'price': 400}]}]}]}, {'id': '9c27acba13d14a8066e297096bce0349', 'sport_key': 'basketball_nba', 'sport_title': 'NBA', 'commence_time': '2024-11-14T00:40:00Z', 'home_team': 'Oklahoma City Thunder', 'away_team': 'New Orleans Pelicans', 'bookmakers': [{'key': 'betmgm', 'title': 'BetMGM', 'last_update': '2024-11-13T19:41:42Z', 'markets': [{'key': 'h2h', 'last_update': '2024-11-13T19:41:42Z', 'outcomes': [{'name': 'New Orleans Pelicans', 'price': 725}, {'name': 'Oklahoma City Thunder', 'price': -1200}]}]}]}, {'id': 'ca77278189a9747eae7bd56344e86485', 'sport_key': 'basketball_nba', 'sport_title': 'NBA', 'commence_time': '2024-11-14T01:10:00Z', 'home_team': 'Milwaukee Bucks', 'away_team': 'Detroit Pistons', 'bookmakers': [{'key': 'betmgm', 'title': 'BetMGM', 'last_update': '2024-11-13T19:41:42Z', 'markets': [{'key': 'h2h', 'last_update': '2024-11-13T19:41:42Z', 'outcomes': [{'name': 'Detroit Pistons', 'price': 220}, {'name': 'Milwaukee Bucks', 'price': -275}]}]}]}, {'id': '521751e36a2efea1e1a05a7ed22120a4', 'sport_key': 'basketball_nba', 'sport_title': 'NBA', 'commence_time': '2024-11-14T01:10:00Z', 'home_team': 'Houston Rockets', 'away_team': 'Los Angeles Clippers', 'bookmakers': [{'key': 'betmgm', 'title': 'BetMGM', 'last_update': '2024-11-13T19:41:42Z', 'markets': [{'key': 'h2h', 'last_update': '2024-11-13T19:41:42Z', 'outcomes': [{'name': 'Houston Rockets', 'price': -185}, {'name': 'Los Angeles Clippers', 'price': 150}]}]}]}, {'id': '3eb19bad0a5843a7a402bded7ee83760', 'sport_key': 'basketball_nba', 'sport_title': 'NBA', 'commence_time': '2024-11-14T01:10:00Z', 'home_team': 'San Antonio Spurs', 'away_team': 'Washington Wizards', 'bookmakers': [{'key': 'betmgm', 'title': 'BetMGM', 'last_update': '2024-11-13T19:41:42Z', 'markets': [{'key': 'h2h', 'last_update': '2024-11-13T19:41:42Z', 'outcomes': [{'name': 'San Antonio Spurs', 'price': -500}, {'name': 'Washington Wizards', 'price': 375}]}]}]}, {'id': 'c64a5e1b02e660dda2a9fdebff5bd591', 'sport_key': 'basketball_nba', 'sport_title': 'NBA', 'commence_time': '2024-11-14T03:10:00Z', 'home_team': 'Los Angeles Lakers', 'away_team': 'Memphis Grizzlies', 'bookmakers': [{'key': 'betmgm', 'title': 'BetMGM', 'last_update': '2024-11-13T19:41:42Z', 'markets': [{'key': 'h2h', 'last_update': '2024-11-13T19:41:42Z', 'outcomes': [{'name': 'Los Angeles Lakers', 'price': -275}, {'name': 'Memphis Grizzlies', 'price': 230}]}]}]}, {'id': 'e6189dd8c7a2ba60a32c5252d17d6de6', 'sport_key': 'basketball_nba', 'sport_title': 'NBA', 'commence_time': '2024-11-14T03:10:00Z', 'home_team': 'Portland Trail Blazers', 'away_team': 'Minnesota Timberwolves', 'bookmakers': [{'key': 'betmgm', 'title': 'BetMGM', 'last_update': '2024-11-13T19:41:42Z', 'markets': [{'key': 'h2h', 'last_update': '2024-11-13T19:41:42Z', 'outcomes': [{'name': 'Minnesota Timberwolves', 'price': -450}, {'name': 'Portland Trail Blazers', 'price': 333}]}]}]}, {'id': 'aaca57d0691d4402964f21d9fa8a0d2c', 'sport_key': 'basketball_nba', 'sport_title': 'NBA', 'commence_time': '2024-11-14T03:10:00Z', 'home_team': 'Sacramento Kings', 'away_team': 'Phoenix Suns', 'bookmakers': [{'key': 'betmgm', 'title': 'BetMGM', 'last_update': '2024-11-13T19:41:42Z', 'markets': [{'key': 'h2h', 'last_update': '2024-11-13T19:41:42Z', 'outcomes': [{'name': 'Phoenix Suns', 'price': 240}, {'name': 'Sacramento Kings', 'price': -300}]}]}]}]
Remaining requests 492
Used requests 8

In [6]:
odds_meta = [
    ['id'],
    # ['has_outrights'],
    ['sport_key'],
    ['sport_title'],
    ['commence_time'],
    ['home_team'],
    ['away_team'],
    ['bookmakers', 'key'],
    ['bookmakers', 'title'],
    ['bookmakers', 'last_update'],
    ['bookmakers', 'markets', 'key'],
    ['bookmakers', 'markets', 'last_update'],
]

df = pd.json_normalize(odds_json, record_path=['bookmakers', 'markets', 'outcomes'], 
            meta=odds_meta, sep='_'
            )

In [7]:
pg.walk(df)

Box(children=(HTML(value='<div id="ifr-pyg-0" style="height: auto">\n    <head>\n        <meta http-equiv="Con…

In [8]:
display(df)

,name,price,id,sport_key,sport_title,commence_time,home_team,away_team,bookmakers_key,bookmakers_title,bookmakers_last_update,bookmakers_markets_key,bookmakers_markets_last_update
0,Indiana Pacers,-115,da66702637cc0413553b92c792a05c50,basketball_nba,NBA,2024-11-14T00:10:00Z,Orlando Magic,Indiana Pacers,betmgm,BetMGM,2024-11-13T19:41:42Z,h2h,2024-11-13T19:41:42Z
1,Orlando Magic,-105,da66702637cc0413553b92c792a05c50,basketball_nba,NBA,2024-11-14T00:10:00Z,Orlando Magic,Indiana Pacers,betmgm,BetMGM,2024-11-13T19:41:42Z,h2h,2024-11-13T19:41:42Z
2,Boston Celtics,-375,8e4ee6d0217de06a9defe24875b1b24e,basketball_nba,NBA,2024-11-14T00:40:00Z,Brooklyn Nets,Boston Celtics,betmgm,BetMGM,2024-11-13T19:41:42Z,h2h,2024-11-13T19:41:42Z
3,Brooklyn Nets,290,8e4ee6d0217de06a9defe24875b1b24e,basketball_nba,NBA,2024-11-14T00:40:00Z,Brooklyn Nets,Boston Celtics,betmgm,BetMGM,2024-11-13T19:41:42Z,h2h,2024-11-13T19:41:42Z
4,Chicago Bulls,230,ca4ada15a7c62966e17f7eecb36b2745,basketball_nba,NBA,2024-11-14T00:40:00Z,New York Knicks,Chicago Bulls,betmgm,BetMGM,2024-11-13T19:41:42Z,h2h,2024-11-13T19:41:42Z
5,New York Knicks,-275,ca4ada15a7c62966e17f7eecb36b2745,basketball_nba,NBA,2024-11-14T00:40:00Z,New York Knicks,Chicago Bulls,betmgm,BetMGM,2024-11-13T19:41:42Z,h2h,2024-11-13T19:41:42Z
6,Cleveland Cavaliers,-550,479ed48e101593d026f662ec12a3c984,basketball_nba,NBA,2024-11-14T00:40:00Z,Philadelphia 76ers,Cleveland Cavaliers,betmgm,BetMGM,2024-11-13T19:41:42Z,h2h,2024-11-13T19:41:42Z
7,Philadelphia 76ers,400,479ed48e101593d026f662ec12a3c984,basketball_nba,NBA,2024-11-14T00:40:00Z,Philadelphia 76ers,Cleveland Cavaliers,betmgm,BetMGM,2024-11-13T19:41:42Z,h2h,2024-11-13T19:41:42Z
8,New Orleans Pelicans,725,9c27acba13d14a8066e297096bce0349,basketball_nba,NBA,2024-11-14T00:40:00Z,Oklahoma City Thunder,New Orleans Pelicans,betmgm,BetMGM,2024-11-13T19:41:42Z,h2h,2024-11-13T19:41:42Z
9,Oklahoma City Thunder,-1200,9c27acba13d14a8066e297096bce0349,basketball_nba,NBA,2024-11-14T00:40:00Z,Oklahoma City Thunder,New Orleans Pelicans,betmgm,BetMGM,2024-11-13T19:41:42Z,h2h,2024-11-13T19:41:42Z
10,Detroit Pistons,220,ca77278189a9747eae7bd56344e86485,basketball_nba,NBA,2024-11-14T01:10:00Z,Milwaukee Bucks,Detroit Pistons,betmgm,BetMGM,2024-11-13T19:41:42Z,h2h,2024-11-13T19:41:42Z
11,Milwaukee Bucks,-275,ca77278189a9747eae7bd56344e86485,basketball_nba,NBA,2024-11-14T01:10:00Z,Milwaukee Bucks,Detroit Pistons,betmgm,BetMGM,2024-11-13T19:41:42Z,h2h,2024-11-13T19:41:42Z
12,Houston Rockets,-185,521751e36a2efea1e1a05a7ed22120a4,basketball_nba,NBA,2024-11-14T01:10:00Z,Houston Rockets,Los Angeles Clippers,betmgm,BetMGM,2024-11-13T19:41:42Z,h2h,2024-11-13T19:41:42Z
13,Los Angeles Clippers,150,521751e36a2efea1e1a05a7ed22120a4,basketball_nba,NBA,2024-11-14T01:10:00Z,Houston Rockets,Los Angeles Clippers,betmgm,BetMGM,2024-11-13T19:41:42Z,h2h,2024-11-13T19:41:42Z
14,San Antonio Spurs,-500,3eb19bad0a5843a7a402bded7ee83760,basketball_nba,NBA,2024-11-14T01:10:00Z,San Antonio Spurs,Washington Wizards,betmgm,BetMGM,2024-11-13T19:41:42Z,h2h,2024-11-13T19:41:42Z
15,Washington Wizards,375,3eb19bad0a5843a7a402bded7ee83760,basketball_nba,NBA,2024-11-14T01:10:00Z,San Antonio Spurs,Washington Wizards,betmgm,BetMGM,2024-11-13T19:41:42Z,h2h,2024-11-13T19:41:42Z
16,Los Angeles Lakers,-275,c64a5e1b02e660dda2a9fdebff5bd591,basketball_nba,NBA,2024-11-14T03:10:00Z,Los Angeles Lakers,Memphis Grizzlies,betmgm,BetMGM,2024-11-13T19:41:42Z,h2h,2024-11-13T19:41:42Z
17,Memphis Grizzlies,230,c64a5e1b02e660dda2a9fdebff5bd591,basketball_nba,NBA,2024-11-14T03:10:00Z,Los Angeles Lakers,Memphis Grizzlies,betmgm,BetMGM,2024-11-13T19:41:42Z,h2h,2024-11-13T19:41:42Z
18,Minnesota Timberwolves,-450,e6189dd8c7a2ba60a32c5252d17d6de6,basketball_nba,NBA,2024-11-14T03:10:00Z,Portland Trail Blazers,Minnesota Timberwolves,betmgm,BetMGM,2024-11-13T19:41:42Z,h2h,2024-11-13T19:41:42Z
19,Portland Trail Blazers,333,e6189dd8c7a2ba60a32c5252d17d6de6,basketball_nba,NBA,2024-11-14T03:10:00Z,Portland Trail Blazers,Minnesota Timberwolves,betmgm,BetMGM,2024-11-13T19:41:42Z,h2h,2024-11-13T19:41:42Z
20,Phoenix Suns,240,aaca57d0691d4402964f21d9fa8a0d2c,basketball_nba,NBA,2024-11-14T03:10:00Z,Sacramento Kings,Phoenix Suns,betmgm,BetMGM,2024-11-13T19:41:42Z,h2h,2024-11-13T19:41:42Z
21,Sacramento Kings,-300,aaca57d0691d4402964f21d9fa8a0d2c,basketball_nba,NBA,2024-11-14T03:10:00Z,Sacramento Kings,Phoenix Suns,betmgm,BetMGM,2024-11-13T19:41:42Z,h2h,2024-11-13T19:41:42Z