In [1]:

import numpy as np
import pandas as pd
import requests
from lib.odds import Odds

ImportError: cannot import name 'odds_api_key' from 'lib.creds' (C:\Users\cwood\Documents\bball_proj\wood-ball\lib\creds.py)

In [24]:
import requests

# An api key is emailed to you when you sign up to a plan
# Get a free API key at https://api.the-odds-api.com/
API_KEY = '2b1fbcaa5cf9bbfca66c986129524664'

SPORT = 'basketball_nba_championship_winner' # use the sport_key from the /sports endpoint below, or use 'upcoming' to see the next 8 games across all sports

REGIONS = 'us' # uk | us | eu | au. Multiple can be specified if comma delimited

MARKETS = 'outrights' # h2h | spreads | totals. Multiple can be specified if comma delimited

ODDS_FORMAT = 'decimal' # decimal | american

DATE_FORMAT = 'iso' # iso | unix

In [25]:
sports_response = requests.get(
    'https://api.the-odds-api.com/v4/sports', 
    params={
        'api_key': API_KEY
    }
)


if sports_response.status_code != 200:
    print(f'Failed to get sports: status_code {sports_response.status_code}, response body {sports_response.text}')

else:
    print('List of in season sports:', sports_response.json())

List of in season sports: [{'key': 'americanfootball_cfl', 'group': 'American Football', 'title': 'CFL', 'description': 'Canadian Football League', 'active': True, 'has_outrights': False}, {'key': 'americanfootball_ncaaf', 'group': 'American Football', 'title': 'NCAAF', 'description': 'US College Football', 'active': True, 'has_outrights': False}, {'key': 'americanfootball_ncaaf_championship_winner', 'group': 'American Football', 'title': 'NCAAF Championship Winner', 'description': 'US College Football Championship Winner', 'active': True, 'has_outrights': True}, {'key': 'americanfootball_nfl', 'group': 'American Football', 'title': 'NFL', 'description': 'US Football', 'active': True, 'has_outrights': False}, {'key': 'americanfootball_nfl_super_bowl_winner', 'group': 'American Football', 'title': 'NFL Super Bowl Winner', 'description': 'Super Bowl Winner 2024/2025', 'active': True, 'has_outrights': True}, {'key': 'americanfootball_ufl', 'group': 'American Football', 'title': 'UFL', 'description': 'United Football League', 'active': True, 'has_outrights': False}, {'key': 'aussierules_afl', 'group': 'Aussie Rules', 'title': 'AFL', 'description': 'Aussie Football', 'active': True, 'has_outrights': False}, {'key': 'baseball_kbo', 'group': 'Baseball', 'title': 'KBO', 'description': 'KBO League', 'active': True, 'has_outrights': False}, {'key': 'baseball_milb', 'group': 'Baseball', 'title': 'MiLB', 'description': 'Minor League Baseball', 'active': True, 'has_outrights': False}, {'key': 'baseball_mlb', 'group': 'Baseball', 'title': 'MLB', 'description': 'Major League Baseball', 'active': True, 'has_outrights': False}, {'key': 'baseball_mlb_world_series_winner', 'group': 'Baseball', 'title': 'MLB World Series Winner', 'description': 'World Series Winner 2024', 'active': True, 'has_outrights': True}, {'key': 'baseball_ncaa', 'group': 'Baseball', 'title': 'NCAA Baseball', 'description': 'US College Baseball', 'active': True, 'has_outrights': False}, {'key': 'baseball_npb', 'group': 'Baseball', 'title': 'NPB', 'description': 'Nippon Professional Baseball', 'active': True, 'has_outrights': False}, {'key': 'basketball_nba', 'group': 'Basketball', 'title': 'NBA', 'description': 'US Basketball', 'active': True, 'has_outrights': False}, {'key': 'basketball_nba_championship_winner', 'group': 'Basketball', 'title': 'NBA Championship Winner', 'description': 'Championship Winner 2024/2025', 'active': True, 'has_outrights': True}, {'key': 'basketball_ncaab_championship_winner', 'group': 'Basketball', 'title': 'NCAAB Championship Winner', 'description': 'US College Basketball Championship Winner', 'active': True, 'has_outrights': True}, {'key': 'basketball_wnba', 'group': 'Basketball', 'title': 'WNBA', 'description': 'US Basketball', 'active': True, 'has_outrights': False}, {'key': 'boxing_boxing', 'group': 'Boxing', 'title': 'Boxing', 'description': 'Boxing Bouts', 'active': True, 'has_outrights': False}, {'key': 'cricket_t20_blast', 'group': 'Cricket', 'title': 'T20 Blast', 'description': 'T20 Blast', 'active': True, 'has_outrights': False}, {'key': 'golf_masters_tournament_winner', 'group': 'Golf', 'title': 'Masters Tournament Winner', 'description': '2025 Winner', 'active': True, 'has_outrights': True}, {'key': 'golf_pga_championship_winner', 'group': 'Golf', 'title': 'PGA Championship Winner', 'description': '2025 Winner', 'active': True, 'has_outrights': True}, {'key': 'golf_the_open_championship_winner', 'group': 'Golf', 'title': 'The Open Winner', 'description': '2024 Winner', 'active': True, 'has_outrights': True}, {'key': 'golf_us_open_winner', 'group': 'Golf', 'title': 'US Open Winner', 'description': '2024 Winner', 'active': True, 'has_outrights': True}, {'key': 'icehockey_nhl', 'group': 'Ice Hockey', 'title': 'NHL', 'description': 'US Ice Hockey', 'active': True, 'has_outrights': False}, {'key': 'icehockey_nhl_championship_winner', 'group': 'Ice Hockey', 'title': 'NHL Championship Winner', 'description': 'Stanley Cup Winner 2023/2024', 'active': True, 'has_outrights': True}, {'key': 'icehockey_sweden_hockey_league', 'group': 'Ice Hockey', 'title': 'SHL', 'description': 'Swedish Hockey League', 'active': True, 'has_outrights': False}, {'key': 'lacrosse_pll', 'group': 'Lacrosse', 'title': 'PLL', 'description': 'Premier Lacrosse League', 'active': True, 'has_outrights': False}, {'key': 'mma_mixed_martial_arts', 'group': 'Mixed Martial Arts', 'title': 'MMA', 'description': 'Mixed Martial Arts', 'active': True, 'has_outrights': False}, {'key': 'politics_us_presidential_election_winner', 'group': 'Politics', 'title': 'US Presidential Elections Winner', 'description': '2024 US Presidential Election Winner', 'active': True, 'has_outrights': True}, {'key': 'rugbyleague_nrl', 'group': 'Rugby League', 'title': 'NRL', 'description': 'Aussie Rugby League', 'active': True, 'has_outrights': False}, {'key': 'soccer_argentina_primera_division', 'group': 'Soccer', 'title': 'Primera División - Argentina', 'description': 'Argentine Primera División', 'active': True, 'has_outrights': False}, {'key': 'soccer_brazil_campeonato', 'group': 'Soccer', 'title': 'Brazil Série A', 'description': 'Brasileirão Série A', 'active': True, 'has_outrights': False}, {'key': 'soccer_brazil_serie_b', 'group': 'Soccer', 'title': 'Brazil Série B', 'description': 'Campeonato Brasileiro Série B', 'active': True, 'has_outrights': False}, {'key': 'soccer_chile_campeonato', 'group': 'Soccer', 'title': 'Primera División - Chile', 'description': 'Campeonato Chileno', 'active': True, 'has_outrights': False}, {'key': 'soccer_china_superleague', 'group': 'Soccer', 'title': 'Super League - China', 'description': 'Chinese Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_conmebol_copa_america', 'group': 'Soccer', 'title': 'Copa América', 'description': 'CONMEBOL Copa América', 'active': True, 'has_outrights': False}, {'key': 'soccer_conmebol_copa_libertadores', 'group': 'Soccer', 'title': 'Copa Libertadores', 'description': 'CONMEBOL Copa Libertadores', 'active': True, 'has_outrights': False}, {'key': 'soccer_fifa_world_cup_winner', 'group': 'Soccer', 'title': 'FIFA World Cup Winner', 'description': 'FIFA World Cup Winner 2026', 'active': True, 'has_outrights': True}, {'key': 'soccer_finland_veikkausliiga', 'group': 'Soccer', 'title': 'Veikkausliiga - Finland', 'description': 'Finnish  Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_japan_j_league', 'group': 'Soccer', 'title': 'J League', 'description': 'Japan Soccer League', 'active': True, 'has_outrights': False}, {'key': 'soccer_korea_kleague1', 'group': 'Soccer', 'title': 'K League 1', 'description': 'Korean Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_mexico_ligamx', 'group': 'Soccer', 'title': 'Liga MX', 'description': 'Mexican Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_norway_eliteserien', 'group': 'Soccer', 'title': 'Eliteserien - Norway', 'description': 'Norwegian Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_sweden_allsvenskan', 'group': 'Soccer', 'title': 'Allsvenskan - Sweden', 'description': 'Swedish Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_sweden_superettan', 'group': 'Soccer', 'title': 'Superettan - Sweden', 'description': 'Swedish Soccer', 'active': True, 'has_outrights': False}, {'key': 'soccer_uefa_european_championship', 'group': 'Soccer', 'title': 'UEFA Euro 2024', 'description': 'UEFA European Championship', 'active': True, 'has_outrights': False}, {'key': 'soccer_usa_mls', 'group': 'Soccer', 'title': 'MLS', 'description': 'Major League Soccer', 'active': True, 'has_outrights': False}]

In [28]:
from rich import print

In [31]:
print(f"[bold red]{sports_response.headers}")

{'Date': 'Fri, 14 Jun 2024 04:50:10 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length':
'1299', 'Connection': 'keep-alive', 'content-encoding': 'gzip', 'X-Requests-Used': '2', 'X-Requests-Remaining':
'498', 'X-Requests-Last': '0', 'vary': 'Accept-Encoding', 'Apigw-Requestid': 'ZVzQXgNYoAMEPSw='}

In [26]:
df = pd.DataFrame(sports_response.json())

,key,group,title,description,active,has_outrights
0,americanfootball_cfl,American Football,CFL,Canadian Football League,True,False
1,americanfootball_ncaaf,American Football,NCAAF,US College Football,True,False
2,americanfootball_ncaaf_championship_winner,American Football,NCAAF Championship Winner,US College Football Championship Winner,True,True
3,americanfootball_nfl,American Football,NFL,US Football,True,False
4,americanfootball_nfl_super_bowl_winner,American Football,NFL Super Bowl Winner,Super Bowl Winner 2024/2025,True,True
5,americanfootball_ufl,American Football,UFL,United Football League,True,False
6,aussierules_afl,Aussie Rules,AFL,Aussie Football,True,False
7,baseball_kbo,Baseball,KBO,KBO League,True,False
8,baseball_milb,Baseball,MiLB,Minor League Baseball,True,False
9,baseball_mlb,Baseball,MLB,Major League Baseball,True,False
10,baseball_mlb_world_series_winner,Baseball,MLB World Series Winner,World Series Winner 2024,True,True
11,baseball_ncaa,Baseball,NCAA Baseball,US College Baseball,True,False
12,baseball_npb,Baseball,NPB,Nippon Professional Baseball,True,False
13,basketball_nba,Basketball,NBA,US Basketball,True,False
14,basketball_nba_championship_winner,Basketball,NBA Championship Winner,Championship Winner 2024/2025,True,True
15,basketball_ncaab_championship_winner,Basketball,NCAAB Championship Winner,US College Basketball Championship Winner,True,True
16,basketball_wnba,Basketball,WNBA,US Basketball,True,False
17,boxing_boxing,Boxing,Boxing,Boxing Bouts,True,False
18,cricket_t20_blast,Cricket,T20 Blast,T20 Blast,True,False
19,golf_masters_tournament_winner,Golf,Masters Tournament Winner,2025 Winner,True,True
20,golf_pga_championship_winner,Golf,PGA Championship Winner,2025 Winner,True,True
21,golf_the_open_championship_winner,Golf,The Open Winner,2024 Winner,True,True
22,golf_us_open_winner,Golf,US Open Winner,2024 Winner,True,True
23,icehockey_nhl,Ice Hockey,NHL,US Ice Hockey,True,False
24,icehockey_nhl_championship_winner,Ice Hockey,NHL Championship Winner,Stanley Cup Winner 2023/2024,True,True
25,icehockey_sweden_hockey_league,Ice Hockey,SHL,Swedish Hockey League,True,False
26,lacrosse_pll,Lacrosse,PLL,Premier Lacrosse League,True,False
27,mma_mixed_martial_arts,Mixed Martial Arts,MMA,Mixed Martial Arts,True,False
28,politics_us_presidential_election_winner,Politics,US Presidential Elections Winner,2024 US Presidential Election Winner,True,True
29,rugbyleague_nrl,Rugby League,NRL,Aussie Rugby League,True,False
30,soccer_argentina_primera_division,Soccer,Primera División - Argentina,Argentine Primera División,True,False
31,soccer_brazil_campeonato,Soccer,Brazil Série A,Brasileirão Série A,True,False
32,soccer_brazil_serie_b,Soccer,Brazil Série B,Campeonato Brasileiro Série B,True,False
33,soccer_chile_campeonato,Soccer,Primera División - Chile,Campeonato Chileno,True,False
34,soccer_china_superleague,Soccer,Super League - China,Chinese Soccer,True,False
35,soccer_conmebol_copa_america,Soccer,Copa América,CONMEBOL Copa América,True,False
36,soccer_conmebol_copa_libertadores,Soccer,Copa Libertadores,CONMEBOL Copa Libertadores,True,False
37,soccer_fifa_world_cup_winner,Soccer,FIFA World Cup Winner,FIFA World Cup Winner 2026,True,True
38,soccer_finland_veikkausliiga,Soccer,Veikkausliiga - Finland,Finnish Soccer,True,False
39,soccer_japan_j_league,Soccer,J League,Japan Soccer League,True,False
40,soccer_korea_kleague1,Soccer,K League 1,Korean Soccer,True,False
41,soccer_mexico_ligamx,Soccer,Liga MX,Mexican Soccer,True,False
42,soccer_norway_eliteserien,Soccer,Eliteserien - Norway,Norwegian Soccer,True,False
43,soccer_sweden_allsvenskan,Soccer,Allsvenskan - Sweden,Swedish Soccer,True,False
44,soccer_sweden_superettan,Soccer,Superettan - Sweden,Swedish Soccer,True,False
45,soccer_uefa_european_championship,Soccer,UEFA Euro 2024,UEFA European Championship,True,False
46,soccer_usa_mls,Soccer,MLS,Major League Soccer,True,False

In [7]:
odds_response = requests.get(
    f'https://api.the-odds-api.com/v4/sports/{SPORT}/odds',
    params={
        'api_key': API_KEY,
        'regions': REGIONS,
        'markets': MARKETS,
        'oddsFormat': ODDS_FORMAT,
        'dateFormat': DATE_FORMAT,
    }
)

if odds_response.status_code != 200:
    print(f'Failed to get odds: status_code {odds_response.status_code}, response body {odds_response.text}')

else:
    odds_json = odds_response.json()
    print('Number of events:', len(odds_json))
    print(odds_json)

    # Check the usage quota
    print('Remaining requests', odds_response.headers['x-requests-remaining'])
    print('Used requests', odds_response.headers['x-requests-used'])

Number of events: 1
[{'id': '7c66e6cf069aa52be1dd7eaa47488403', 'has_outrights': True, 'sport_key': 'basketball_nba_championship_winner', 'sport_title': 'NBA Championship Winner', 'commence_time': '2024-06-19T22:00:15Z', 'home_team': None, 'away_team': None, 'bookmakers': [{'key': 'draftkings', 'title': 'DraftKings', 'last_update': '2024-06-14T04:28:36Z', 'markets': [{'key': 'outrights', 'last_update': '2024-06-14T04:28:36Z', 'outcomes': [{'name': 'Boston Celtics', 'price': 1.03}, {'name': 'Dallas Mavericks', 'price': 18.0}]}]}, {'key': 'betrivers', 'title': 'BetRivers', 'last_update': '2024-06-14T04:25:36Z', 'markets': [{'key': 'outrights', 'last_update': '2024-06-14T04:25:36Z', 'outcomes': [{'name': 'Boston Celtics', 'price': 1.01}, {'name': 'Dallas Mavericks', 'price': 21.0}]}]}, {'key': 'bovada', 'title': 'Bovada', 'last_update': '2024-06-14T04:27:08Z', 'markets': [{'key': 'outrights', 'last_update': '2024-06-14T04:27:08Z', 'outcomes': [{'name': 'Boston Celtics', 'price': 1.02}, {'name': 'Dallas Mavericks', 'price': 21.0}]}]}, {'key': 'williamhill_us', 'title': 'Caesars', 'last_update': '2024-06-14T04:23:16Z', 'markets': [{'key': 'outrights', 'last_update': '2024-06-14T04:23:16Z', 'outcomes': [{'name': 'Boston Celtics', 'price': 1.01}, {'name': 'Dallas Mavericks', 'price': 21.0}]}]}, {'key': 'betmgm', 'title': 'BetMGM', 'last_update': '2024-06-14T04:24:03Z', 'markets': [{'key': 'outrights', 'last_update': '2024-06-14T04:24:03Z', 'outcomes': [{'name': 'Boston Celtics', 'price': 1.01}, {'name': 'Dallas Mavericks', 'price': 21.0}]}]}]}]
Remaining requests 498
Used requests 2

In [14]:
df1 = odds_response.json()
df1

,id,has_outrights,sport_key,sport_title,commence_time,home_team,away_team,bookmakers
0,7c66e6cf069aa52be1dd7eaa47488403,True,basketball_nba_championship_winner,NBA Championship Winner,2024-06-19T22:00:15Z,None,None,"[{'key': 'draftkings', 'title': 'DraftKings', ..."

In [8]:
odds_meta = [
    ['id'],
    ['has_outrights'],
    ['sport_key'],
    ['sport_title'],
    ['commence_time'],
    ['home_team'],
    ['away_team'],
    ['bookmakers', 'key'],
    ['bookmakers', 'title'],
    ['bookmakers', 'last_update'],
    ['bookmakers', 'markets', 'key'],
    ['bookmakers', 'markets', 'last_update']
]

In [9]:
df1 = pd.json_normalize(odds_json, record_path=['bookmakers', 'markets', 'outcomes'], 
                    meta=odds_meta, sep='_'
                    )

In [4]:
import duckdb

conn = duckdb.connect('X:\\nba_data\\odds_data\\odds.db')

In [ ]:
COPY
    (SELECT * FROM tbl)
    TO 'result-snappy.parquet'
    (FORMAT 'parquet');

In [15]:
conn.sql('select * from df1')

┌──────────────────┬────────┬──────────────────────┬───┬──────────────────────┬──────────────────────┐
│       name       │ price  │          id          │ … │ bookmakers_markets…  │ bookmakers_markets…  │
│     varchar      │ double │       varchar        │   │       varchar        │       varchar        │
├──────────────────┼────────┼──────────────────────┼───┼──────────────────────┼──────────────────────┤
│ Boston Celtics   │   1.03 │ 7c66e6cf069aa52be1…  │ … │ outrights            │ 2024-06-14T04:28:36Z │
│ Dallas Mavericks │   18.0 │ 7c66e6cf069aa52be1…  │ … │ outrights            │ 2024-06-14T04:28:36Z │
│ Boston Celtics   │   1.01 │ 7c66e6cf069aa52be1…  │ … │ outrights            │ 2024-06-14T04:25:36Z │
│ Dallas Mavericks │   21.0 │ 7c66e6cf069aa52be1…  │ … │ outrights            │ 2024-06-14T04:25:36Z │
│ Boston Celtics   │   1.02 │ 7c66e6cf069aa52be1…  │ … │ outrights            │ 2024-06-14T04:27:08Z │
│ Dallas Mavericks │   21.0 │ 7c66e6cf069aa52be1…  │ … │ outrights            │ 2024-06-14T04:27:08Z │
│ Boston Celtics   │   1.01 │ 7c66e6cf069aa52be1…  │ … │ outrights            │ 2024-06-14T04:23:16Z │
│ Dallas Mavericks │   21.0 │ 7c66e6cf069aa52be1…  │ … │ outrights            │ 2024-06-14T04:23:16Z │
│ Boston Celtics   │   1.01 │ 7c66e6cf069aa52be1…  │ … │ outrights            │ 2024-06-14T04:24:03Z │
│ Dallas Mavericks │   21.0 │ 7c66e6cf069aa52be1…  │ … │ outrights            │ 2024-06-14T04:24:03Z │
├──────────────────┴────────┴──────────────────────┴───┴──────────────────────┴──────────────────────┤
│ 10 rows                                                                       14 columns (5 shown) │
└────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [16]:
conn.sql("create table nba_champ_odds as select * from df1")

In [23]:
conn.sql('select column_name from information_schema.columns where table_name = \'nba_champ_odds\'')

┌────────────────────────────────┐
│          column_name           │
│            varchar             │
├────────────────────────────────┤
│ name                           │
│ price                          │
│ id                             │
│ has_outrights                  │
│ sport_key                      │
│ sport_title                    │
│ commence_time                  │
│ home_team                      │
│ away_team                      │
│ bookmakers_key                 │
│ bookmakers_title               │
│ bookmakers_last_update         │
│ bookmakers_markets_key         │
│ bookmakers_markets_last_update │
├────────────────────────────────┤
│            14 rows             │
└────────────────────────────────┘